import type { Ad, Advertiser, Project, Watchlist } from "./models";
export const projects: Project[] = [
  { id: "all", name: "Tous les projets", accent: "#7c6bf2" }, { id: "auryel", name: "Auryel", accent: "#67e8f9" }, { id: "cee", name: "CEE / SSC / PAC", accent: "#fbbf24" }, { id: "feaseweb", name: "Feaseweb", accent: "#fb7185" },
];
export const advertisers: Advertiser[] = [
  { id: "helios", name: "Helios Habitat", category: "Rénovation énergétique", country: "FR" }, { id: "nurture", name: "Nurture Club", category: "Bien-être", country: "FR" }, { id: "studio-nova", name: "Studio Nova", category: "Éducation", country: "BE" }, { id: "greenly", name: "Greenly", category: "Fintech", country: "FR" },
];
const image = (url: string) => "https://images.unsplash.com/" + url + "?w=900&q=85";
export const ads: Ad[] = [
  { id: "ad-001", projectId: "cee", platform: "meta", advertiserId: "helios", externalId: "meta_88214", primaryText: "Votre maison perd-elle de la chaleur sans que vous le sachiez ? Découvrez le diagnostic offert.", headline: "Le diagnostic énergétique offert", cta: "En savoir plus", firstDetectedAt: "2026-08-04", lastDetectedAt: "2026-09-28", status: "active", countries: ["FR"], creative: { id: "cr-001", format: "image", dimensions: { width: 1080, height: 1350 }, thumbnailUrl: image("photo-1564013799919-ab600027ffc6") }, publicMetrics: { impressions: "100K–250K", reactions: "1.8K", comments: "142" }, signalScore: 86, tags: ["avant / après", "preuve", "lead gen"] },
  { id: "ad-002", projectId: "auryel", platform: "tiktok", advertiserId: "nurture", externalId: "tt_10128", primaryText: "POV : tu comprends enfin pourquoi ton énergie tombe à 15h.", headline: "Le rituel qui change tout", cta: "Découvrir", firstDetectedAt: "2026-08-19", lastDetectedAt: "2026-09-28", status: "active", countries: ["FR", "BE"], creative: { id: "cr-002", format: "video", dimensions: { width: 1080, height: 1920 }, durationSeconds: 23, thumbnailUrl: image("photo-1499209974431-9dddcece7f88") }, publicMetrics: { impressions: "50K–100K", reactions: "4.2K", comments: "318" }, signalScore: 78, tags: ["UGC", "POV", "routine"] },
  { id: "ad-003", projectId: "feaseweb", platform: "meta", advertiserId: "studio-nova", externalId: "meta_77419", primaryText: "Une idée claire vaut mieux que 10 outils. Voici notre méthode pour passer de l'intention au lancement.", headline: "Lancez votre projet avec méthode", cta: "S'inscrire", firstDetectedAt: "2026-06-11", lastDetectedAt: "2026-09-27", status: "active", countries: ["FR", "BE", "CH"], creative: { id: "cr-003", format: "image", dimensions: { width: 1080, height: 1080 }, thumbnailUrl: image("photo-1553877522-43269d4ea984") }, publicMetrics: { impressions: "250K–500K", reactions: "6.7K", comments: "503" }, signalScore: 91, tags: ["framework", "autorité", "carrousel"] },
  { id: "ad-004", projectId: "auryel", platform: "youtube", advertiserId: "greenly", externalId: "yt_91208", primaryText: "Ce que votre banque ne vous montre pas sur vos dépenses quotidiennes.", headline: "Reprenez le contrôle", cta: "Commencer", firstDetectedAt: "2026-09-02", lastDetectedAt: "2026-09-28", status: "active", countries: ["FR"], creative: { id: "cr-004", format: "video", dimensions: { width: 1920, height: 1080 }, durationSeconds: 31, thumbnailUrl: image("photo-1556742049-0cfed4f6a45d") }, publicMetrics: { impressions: "25K–50K", reactions: "820", comments: "62" }, signalScore: 72, tags: ["curiosité", "chiffres", "problème"] },
];
export const watchlists: Watchlist[] = [
  { id: "wl-1", projectId: "cee", name: "Rénovation & PAC", keywords: ["pompe à chaleur", "isolation"], advertiserIds: ["helios"], active: true }, { id: "wl-2", projectId: "feaseweb", name: "Agences & SaaS", keywords: ["lancement", "acquisition"], advertiserIds: ["studio-nova"], active: true }, { id: "wl-3", projectId: "auryel", name: "Bien-être", keywords: ["routine", "énergie"], advertiserIds: ["nurture"], active: true },
];
